from pathlib import Path
import sys

root = Path(sys.argv[1]).resolve()
remote = root / 'TrafficMonitor' / 'RemoteMonitor.cpp'

r = remote.read_text(encoding='utf-8-sig')
r = r.replace('Tailscale / SSH Server [1.86.6]', 'Tailscale / SSH Server [1.86.7]')
r = r.replace('remote monitor 1.86.6 start', 'remote monitor 1.86.7 start')
remote.write_text(r, encoding='utf-8-sig')

print('TrafficMonitor 1.86.7 version marker applied; remote text style is generated by patch_icons.py')
